import { jsPDF } from "jspdf";
import type { Results } from "../domain/alliance-combinations";
import { formatMoney } from "@/lib/currency";

export interface PdfReportOptions {
  title?: string;
  reportHeading?: string;
  tendererNames?: string[];
  contractNames?: string[];
  whatIf?: { changes: Array<{ t: number; c: number; tier: number; deltaPct: number }> };
  forced?: (number | null)[];
  forbidden?: boolean[][];
  selectedContracts?: number[];
}

type Orientation = "portrait" | "landscape";
type Align = "left" | "center" | "right";
type Column = { label: string; width: number; align?: Align };

const PAGE = {
  portrait: { width: 595.28, height: 841.89 },
  landscape: { width: 841.89, height: 595.28 },
} as const;
const MARGIN = 38;
const COLORS = {
  ink: [25, 39, 52] as const,
  muted: [93, 109, 124] as const,
  teal: [0, 137, 157] as const,
  tealSoft: [229, 247, 249] as const,
  pink: [255, 94, 147] as const,
  pinkSoft: [255, 238, 244] as const,
  green: [27, 144, 90] as const,
  greenSoft: [231, 248, 239] as const,
  amber: [178, 111, 0] as const,
  graySoft: [229, 231, 235] as const,
  stripe: [247, 250, 252] as const,
  line: [218, 226, 232] as const,
  white: [255, 255, 255] as const,
};

const rgb = (doc: jsPDF, color: readonly [number, number, number]) => doc.setTextColor(...color);
const fill = (doc: jsPDF, color: readonly [number, number, number]) => doc.setFillColor(...color);
const stroke = (doc: jsPDF, color: readonly [number, number, number]) => doc.setDrawColor(...color);
const pageSize = (orientation: Orientation) => PAGE[orientation];
const contentWidth = (orientation: Orientation) => pageSize(orientation).width - MARGIN * 2;
const money = (value: number) => formatMoney(value);
const labelFor = (names: string[] | undefined, index: number, prefix: string) => names?.[index]?.trim() || `${prefix}${index + 1}`;
const tenderer = (names: string[] | undefined, index: number) => labelFor(names, index, "T");
const contract = (names: string[] | undefined, index: number) => labelFor(names, index, "C");
const localDateStamp = (date: Date) => {
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}`;
};
const lowestBase = (results: Results, c: number) => {
  const values = results.prices.map((row) => row?.[c] ?? 0).filter((v) => v > 0);
  return values.length ? Math.min(...values) : 0;
};

const headerFooter = (doc: jsPDF, orientation: Orientation, title: string, page: number) => {
  const p = pageSize(orientation);
  fill(doc, COLORS.teal);
  doc.rect(0, 0, p.width, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  rgb(doc, COLORS.muted);
  doc.text(title, MARGIN, 24);
  doc.setFont("helvetica", "normal");
  doc.text(`Alliance report  |  ${page}`, p.width - MARGIN, 24, { align: "right" });
  stroke(doc, COLORS.line);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, p.height - 26, p.width - MARGIN, p.height - 26);
  doc.setFontSize(7);
  doc.text("Generated by Alliance Combinations Calculator", MARGIN, p.height - 14);
  doc.text("Confidential working report", p.width - MARGIN, p.height - 14, { align: "right" });
};

const sectionTitle = (doc: jsPDF, orientation: Orientation, title: string, subtitle?: string, y = 52) => {
  const p = pageSize(orientation);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  rgb(doc, COLORS.ink);
  doc.text(title, MARGIN, y);
  fill(doc, COLORS.teal);
  doc.rect(MARGIN, y + 9, 42, 3, "F");
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    rgb(doc, COLORS.muted);
    doc.text(subtitle, MARGIN, y + 28, { maxWidth: p.width - MARGIN * 2 });
    return y + 46;
  }
  return y + 28;
};

const card = (doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value: string, tone: "teal" | "green" | "pink" | "neutral") => {
  const bg = tone === "teal" ? COLORS.tealSoft : tone === "green" ? COLORS.greenSoft : tone === "pink" ? COLORS.pinkSoft : COLORS.stripe;
  const accent = tone === "teal" ? COLORS.teal : tone === "green" ? COLORS.green : tone === "pink" ? COLORS.pink : COLORS.line;
  fill(doc, bg);
  doc.roundedRect(x, y, w, h, 7, 7, "F");
  fill(doc, accent);
  doc.roundedRect(x, y, 4, h, 2, 2, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  rgb(doc, COLORS.muted);
  doc.text(label, x + 14, y + 17);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  rgb(doc, COLORS.ink);
  doc.text(value, x + 14, y + 39);
};

const drawTable = (doc: jsPDF, orientation: Orientation, columns: Column[], rows: string[][], startY: number, options: { fontSize?: number; rowHeight?: number; headerFill?: readonly [number, number, number]; highlightRows?: Set<number>; highlightCells?: Set<string>; cellFills?: Map<string, readonly [number, number, number]> } = {}) => {
  const fontSize = options.fontSize ?? 7.5;
  const rowHeight = options.rowHeight ?? 17;
  const available = contentWidth(orientation);
  const total = columns.reduce((sum, col) => sum + col.width, 0);
  const scale = total > available ? available / total : 1;
  const cols = columns.map((col) => ({ ...col, width: col.width * scale }));
  const x0 = MARGIN;
  const headerHeight = 25;
  let y = startY;
  const drawHeader = () => {
    fill(doc, options.headerFill ?? COLORS.ink);
    doc.roundedRect(x0, y, available, headerHeight, 4, 4, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(fontSize);
    rgb(doc, COLORS.white);
    let x = x0;
    cols.forEach((col) => {
      const align = col.align ?? "left";
      const text = col.label.length > 24 ? `${col.label.slice(0, 22)}...` : col.label;
      doc.text(text, align === "right" ? x + col.width - 5 : align === "center" ? x + col.width / 2 : x + 5, y + 16, { align });
      x += col.width;
    });
    y += headerHeight;
  };
  drawHeader();
  rows.forEach((row, rowIndex) => {
    if (y + rowHeight > pageSize(orientation).height - 38) {
      doc.addPage("a4", orientation);
      headerFooter(doc, orientation, "Alliance Combinations Report", doc.getNumberOfPages());
      y = 48;
      drawHeader();
    }
    const highlighted = options.highlightRows?.has(rowIndex);
    fill(doc, highlighted ? COLORS.greenSoft : rowIndex % 2 ? COLORS.stripe : COLORS.white);
    doc.rect(x0, y, available, rowHeight, "F");
    stroke(doc, COLORS.line);
    doc.line(x0, y + rowHeight, x0 + available, y + rowHeight);
    doc.setFont("helvetica", highlighted ? "bold" : "normal");
    rgb(doc, highlighted ? COLORS.green : COLORS.ink);
    let x = x0;
    cols.forEach((col, i) => {
      const align = col.align ?? "left";
      const text = String(row[i] ?? "");
      const cellFill = options.cellFills?.get(`${rowIndex}:${i}`);
      const cellHighlighted = options.highlightCells?.has(`${rowIndex}:${i}`) === true;
      if (cellFill || cellHighlighted) {
        fill(doc, cellFill ?? COLORS.tealSoft);
        doc.roundedRect(x + 2, y + 2, col.width - 4, rowHeight - 4, 3, 3, "F");
      }
      const lines = text.split("\n");
      const textY = lines.length > 1 ? y + 9 : y + 11;
      doc.text(lines.slice(0, 2), align === "right" ? x + col.width - 5 : align === "center" ? x + col.width / 2 : x + 5, textY, { align, lineHeightFactor: 1.15 });
      x += col.width;
    });
    y += rowHeight;
  });
  return y + 10;
};

export const generateResultsPdf = async (results: Results, opts: PdfReportOptions = {}): Promise<Blob> => {
  const title = "Alliance Combinations Report";
  const reportHeading = opts.reportHeading?.trim() || "Alliance decision summary";
  const m = results.prices.length;
  const n = results.prices[0]?.length ?? 0;
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  let page = 1;
  let orientation: Orientation = "portrait";
  headerFooter(doc, orientation, title, page);
  let y = 72;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  rgb(doc, COLORS.ink);
  doc.text(title, MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  rgb(doc, COLORS.ink);
  doc.text(reportHeading, MARGIN, y + 22);
  doc.setFontSize(10);
  rgb(doc, COLORS.muted);
  const generatedAt = new Date();
  const reportDate = generatedAt.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  doc.text(`Report Generated on ${reportDate}`, MARGIN, y + 42);
  fill(doc, COLORS.teal);
  doc.rect(MARGIN, y + 59, 86, 5, "F");
  y += 98;
  if (opts.whatIf?.changes?.length) {
    const lines = opts.whatIf.changes.map((change, i) => `${i + 1}. ${contract(opts.contractNames, change.c)} / ${tenderer(opts.tendererNames, change.t)} — DoP ${change.tier + 1}, ${change.deltaPct >= 0 ? "+" : ""}${change.deltaPct}%`);
    const boxH = 34 + lines.length * 13;
    fill(doc, COLORS.tealSoft);
    doc.roundedRect(MARGIN, y, contentWidth(orientation), boxH, 6, 6, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); rgb(doc, COLORS.teal);
    doc.text("What-if scenario applied", MARGIN + 14, y + 18);
    doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); rgb(doc, COLORS.ink);
    doc.text(lines, MARGIN + 14, y + 34, { lineHeightFactor: 1.35 });
    y += boxH + 16;
  }
  y = sectionTitle(doc, orientation, "Results Summary", "A concise view of the best valid alliance configuration and the search behind it.", y);
  const gap = 10;
  const cardW = (contentWidth(orientation) - gap * 2) / 3;
  card(doc, MARGIN, y, cardW, 58, "Total lowest base", money(results.totalLowestBase), "pink");
  card(doc, MARGIN + cardW + gap, y, cardW, 58, "Best alliance total", money(results.totalSelectedDiscounted), "teal");
  card(doc, MARGIN + (cardW + gap) * 2, y, cardW, 58, "Cost saving", money(results.costSaving), "green");
  y += 78;
  fill(doc, COLORS.tealSoft);
  doc.roundedRect(MARGIN, y, contentWidth(orientation), 54, 6, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  rgb(doc, COLORS.teal);
  doc.text("Decision readout", MARGIN + 14, y + 19);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  rgb(doc, COLORS.ink);
  const constrained = (opts.forced?.some((v) => v != null) ?? false) || (opts.forbidden?.some((row) => row.some(Boolean)) ?? false);
  const readout = results.status === "infeasible"
    ? "No compliant combination was found. No saving is reported because every selected contract must remain within its original lowest submitted base price."
    : results.bestCombo
      ? `The recommended alliance is ${money(results.totalSelectedDiscounted)}, saving ${money(results.costSaving)} against the standalone base minimum.${constrained ? " Award constraints were applied." : ""} ${results.nicheCombos.length ? `${results.nicheCombos.length} niche optimization${results.nicheCombos.length === 1 ? " is" : "s are"} also available for review.` : "No niche optimization was identified."}`
      : "No valid combination was found for the current input grid.";
  doc.text(doc.splitTextToSize(readout, contentWidth(orientation) - 28), MARGIN + 14, y + 34);

  orientation = "landscape";
  doc.addPage("a4", orientation);
  page++;
  headerFooter(doc, orientation, title, page);
  y = sectionTitle(doc, orientation, "Base Prices Reference", "Lowest standalone bid per contract is the validity ceiling used by the calculator.");
  const baseRows = Array.from({ length: m }, (_, t) => {
    const row = results.prices[t] ?? [];
    const values = Array.from({ length: n }, (_, c) => row[c] > 0 ? money(row[c]) : "Declined");
    const total = row.reduce((sum, value) => sum + (value > 0 ? value : 0), 0);
    return [tenderer(opts.tendererNames, t), ...values, money(total)];
  });
  const baseCellFills = new Map<string, readonly [number, number, number]>();
  for (let t = 0; t < m; t++) {
    for (let c = 0; c < n; c++) {
      const value = results.prices[t]?.[c] ?? 0;
      if (value > 0 && value === lowestBase(results, c)) baseCellFills.set(`${t}:${c + 1}`, COLORS.pinkSoft);
    }
  }
  y = drawTable(doc, orientation, [{ label: "Tenderer", width: 120 }, ...Array.from({ length: n }, (_, c) => ({ label: contract(opts.contractNames, c), width: 88 })), { label: "Total", width: 90, align: "right" }], baseRows, y, { fontSize: 7.5, rowHeight: 20, headerFill: COLORS.ink, cellFills: baseCellFills });
  const baseY = y + 2;
  fill(doc, COLORS.pinkSoft);
  doc.roundedRect(MARGIN, baseY, contentWidth(orientation), 32, 5, 5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  rgb(doc, COLORS.pink);
  doc.text("Lowest base by contract", MARGIN + 10, baseY + 13);
  doc.setFont("helvetica", "normal");
  rgb(doc, COLORS.ink);
  const lowestBaseDetails = Array.from({ length: n }, (_, c) => {
    const value = lowestBase(results, c);
    const winner = results.prices.findIndex((row) => (row?.[c] ?? 0) === value && value > 0);
    return `${contract(opts.contractNames, c)}: ${winner >= 0 ? tenderer(opts.tendererNames, winner) : "No bid"} ${money(value)}`;
  });
  doc.text(lowestBaseDetails.join("   |   "), MARGIN + 10, baseY + 25);

  doc.addPage("a4", orientation);
  page++;
  headerFooter(doc, orientation, title, page);
  y = sectionTitle(doc, orientation, "Discounts and Amounts Matrix Breakdown", "Each cell shows the discounted amount and percentage for a tenderer, contract, and DoP.");
  const discountRows: string[][] = [];
  const discountCellFills = new Map<string, readonly [number, number, number]>();
  for (let t = 0; t < m; t++) {
    for (let d = 0; d < n; d++) {
      const rowIndex = discountRows.length;
      const row = [d === 0 ? tenderer(opts.tendererNames, t) : "", `DoP ${d + 1}`];
      for (let c = 0; c < n; c++) {
        const base = results.prices[t]?.[c] ?? 0;
        if (!base) { row.push("-"); continue; }
        const pct = results.discounts[t]?.[c]?.[d] ?? 0;
        const amount = base * (1 - pct / 100);
        row.push(`${money(amount)} (${pct.toFixed(2)}%)`);
        const selectedTier = results.bestCombo?.assignment?.[c] === t
          ? (results.bestCombo.tendererCounts[t] ?? 0) - 1
          : -1;
        if (d === selectedTier) discountCellFills.set(`${rowIndex}:${c + 2}`, COLORS.tealSoft);
        else if (amount > lowestBase(results, c)) discountCellFills.set(`${rowIndex}:${c + 2}`, COLORS.graySoft);
      }
      discountRows.push(row);
    }
  }
  drawTable(doc, orientation, [{ label: "Tenderer", width: 110 }, { label: "DoP", width: 65, align: "center" as const }, ...Array.from({ length: n }, (_, c) => ({ label: contract(opts.contractNames, c), width: 105, align: "center" as const }))], discountRows, y, { fontSize: 7, rowHeight: 18, headerFill: COLORS.teal, cellFills: discountCellFills });

  doc.addPage("a4", orientation);
  page++;
  headerFooter(doc, orientation, title, page);
  y = sectionTitle(doc, orientation, "Best Combination Award Breakdown", "Cyan highlights the award made by the cheapest valid configuration; variance is measured against the base minimum.");
  const best = results.bestCombo;
  if (best) {
    const awardRows = Array.from({ length: m }, (_, t) => {
      const cells = Array.from({ length: n }, (_, c) => best.assignment[c] === t ? money(best.contractCosts[c]) : "-");
      const tendererTotal = best.contractCosts.reduce((sum, cost, c) => sum + (best.assignment[c] === t ? cost : 0), 0);
      return [tenderer(opts.tendererNames, t), ...cells, tendererTotal ? money(tendererTotal) : "-"];
    });
    const highlightCells = new Set<string>();
    best.assignment.forEach((t, c) => {
      if (t >= 0) {
        const rowIndex = t;
        highlightCells.add(`${rowIndex}:${c + 1}`);
      }
    });
    y = drawTable(doc, orientation, [{ label: "Tenderer", width: 120 }, ...Array.from({ length: n }, (_, c) => ({ label: contract(opts.contractNames, c), width: 90, align: "center" as const })), { label: "Award total", width: 100, align: "right" as const }], awardRows, y, { fontSize: 7.5, rowHeight: 22, headerFill: COLORS.teal, highlightCells });
    y = drawTable(doc, orientation, [{ label: "", width: 120 }, ...Array.from({ length: n }, () => ({ label: "", width: 90, align: "center" as const })), { label: "", width: 100, align: "right" as const }], [["Total", ...best.contractCosts.map((cost) => money(cost)), money(best.total)]], y, { fontSize: 8, rowHeight: 24, headerFill: COLORS.ink });
    fill(doc, COLORS.greenSoft);
    doc.roundedRect(MARGIN, y + 2, contentWidth(orientation), 36, 5, 5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    rgb(doc, COLORS.green);
    const awardSummary = best.tendererCounts
      .map((count, t) => count > 0 ? `${tenderer(opts.tendererNames, t)}: ${count} contract${count === 1 ? "" : "s"}` : "")
      .filter(Boolean)
      .join("   |   ");
    doc.text(`Award total ${money(best.total)}  |  Saving ${money(results.costSaving)}  |  Awards: ${awardSummary || "none"}`, MARGIN + 10, y + 24);
  } else {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    rgb(doc, COLORS.muted);
    doc.text("No valid combination was found.", MARGIN, y + 20);
  }

  doc.addPage("a4", orientation);
  page++;
  headerFooter(doc, orientation, title, page);
  y = sectionTitle(doc, orientation, "Strategy Matrix Explorer", results.combinationsTruncated
    ? "The grid was solved exactly with a scalable best-award algorithm; the full assignment set was not materialized."
    : `All ${results.combinations.length.toLocaleString()} valid scenarios, ranked by grand total. Best and niche strategies are tagged for quick review.`);
  const compact = (value: string, max = 14) => value.length > max ? `${value.slice(0, max - 1)}.` : value;
  const strategyRows = results.combinations.map((combo, index) => {
    const profile = combo.isGlobalBest ? "GLOBAL BEST" : combo.isNicheOptimization ? "NICHE" : "SPLIT VARIANT";
    const cells = Array.from({ length: n }, (_, c) => {
      const t = combo.assignment[c];
      return t >= 0 ? `${compact(tenderer(opts.tendererNames, t))}\n${money(combo.contractCosts[c] ?? 0)}` : "-";
    });
    const savings = Math.max(0, results.totalLowestBase - combo.total);
    return [String(index + 1), profile, ...cells, money(combo.total), savings ? `+${money(savings)}` : money(0)];
  });
  const bestRows = new Set(results.combinations.map((combo, index) => combo.isGlobalBest ? index : -1).filter((index) => index >= 0));
  drawTable(doc, orientation, [{ label: "#", width: 28, align: "center" }, { label: "Profile", width: 82 }, ...Array.from({ length: n }, (_, c) => ({ label: contract(opts.contractNames, c), width: 95 })), { label: "Grand total", width: 80, align: "right" }, { label: "Net savings", width: 80, align: "right" }], strategyRows, y, { fontSize: 6.3, rowHeight: 30, headerFill: COLORS.ink, highlightRows: bestRows });

  if (results.nicheCombos.length > 0) {
    doc.addPage("a4", orientation);
    page++;
    headerFooter(doc, orientation, title, page);
    y = sectionTitle(doc, orientation, "Niche Optimization Appendix", "Configurations where a tenderer wins every contract in a limited bid pool.");
    const nicheRows = results.nicheCombos.map((combo, i) => [String(i + 1), money(combo.total), Array.from({ length: n }, (_, c) => `${contract(opts.contractNames, c)}: ${tenderer(opts.tendererNames, combo.assignment[c])}`).join(" | "), combo.tendererCounts.join(", ")]);
    drawTable(doc, orientation, [{ label: "#", width: 28, align: "center" }, { label: "Total", width: 80, align: "right" }, { label: "Assignment", width: 430 }, { label: "Win counts", width: 100, align: "center" }], nicheRows, y, { fontSize: 7.5, rowHeight: 24, headerFill: COLORS.amber });
  }

  return doc.output("blob");
};

export const downloadResultsPdf = async (results: Results, opts: PdfReportOptions = {}): Promise<void> => {
  if (typeof document === "undefined") throw new Error("downloadResultsPdf requires a DOM environment (browser)");
  const stamp = localDateStamp(new Date());
  const filename = `Alliance Combinations Report_${stamp}.pdf`;
  const blob = await generateResultsPdf(results, opts);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
};
